FROM sourcegraph/src-cli:3.16.1@sha256:b5dd688d25557eaa5fb0ec33cf2cc15a87bc72a7f5d9efa6d5e461644e93ac09 AS src-cli

FROM node:15.14-alpine3.10@sha256:7289e0545da1c88aa84d98e77beead2ea1ba5a12c9cb28fd756955d917d69bcd

RUN apk add --no-cache git bash curl ca-certificates python3 make libstdc++ libgcc gcc g++ pkgconfig python

COPY --from=src-cli /usr/bin/src /usr/bin

RUN npm i -g n

RUN npm install -g @sourcegraph/lsif-tsc

CMD ["/bin/sh"]
