FROM sourcegraph/src-cli:3.30.4@sha256:76ee253f9ba6ed1a8fdc46ab1e3f333ea0813841d34feb1aa9b8b57edce4eaab AS src-cli

FROM node:17.4.0-alpine3.14@sha256:584a81841266139f2e3afffb6fcdd52a6f1dab21dfad96d4f4c61f5be8df1d59

ENV NODE_OPTIONS=--max-old-space-size=4096

RUN apk add --no-cache git bash curl ca-certificates python3 make libstdc++ libgcc gcc g++ pkgconfig python2 automake autoconf

COPY --from=src-cli /usr/bin/src /usr/bin

RUN npm install --global n@latest @sourcegraph/lsif-tsc@latest

CMD ["/bin/sh"]
