FROM sourcegraph/src-cli:3.42.1@sha256:6e22245df75b4e63c1afce74bd59b807837949d554c4432033a9b573c31fd712 AS src-cli

FROM node:14.17.4-alpine3.14@sha256:60a5e65ced8bad91a4c57c05a474baa01182b2b773eb50380e4a90ad4b3e6358

ENV NODE_OPTIONS=--max-old-space-size=4096

RUN apk add --no-cache git bash curl ca-certificates python3 make libstdc++ libgcc gcc g++ pkgconfig python2 automake autoconf

COPY --from=src-cli /usr/bin/src /usr/bin

RUN npm install --global n@latest @sourcegraph/lsif-tsc@latest

CMD ["/bin/sh"]
