name: LSIF
on:
  - push
jobs:
  lsif-ts:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2
      - name: Install dependencies
        run: yarn install
      - name: Generate LSIF data
        run: lsif-tsc -p .
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
